### ISSUE TITLE
TFRS - wrong labels showing in confirmation modal window when analyst recommends recording a transfer

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/tfrs#2789] opened 2024-01-11 17:44 UTC
**Describe the Bug**
The wrong labels are showing in the confirmation modal window when the gov't analyst recommends recording a transfer within the TFRS January release, dev environment. 

The modal window currently says "Are you sure you want to recommend issuance of compliance units for this transfer?" and then includes a button label of "Recommend issuance". 

The modal window should say, "Are you sure you want to recommend recording this transfer?" and the button label should say "Recommend recording transfer". 

**Screenshot of current labels:**
<img width="1590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3E4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb99eeaf53652c0af63f3615162c373495521025/Screenshot%202024-01-11%20093836.png" alt="Screenshot 2024-01-11 093836.png" />

**Implications**
Wrong labels in January release

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR user; Gov't analyst role; TFRS Jan release, dev env
1. Go to the Transaction page
2. Click on a Transfer with the Submitted status
3. Click on the Recommend recording transfer button

**Other considerations:**
As a FYI, the New Initiative Agreement Issuance feature (formerly New Part 3 Award) uses similar language in the confirmation modal window when the analyst is recommending the approval of an issuance from an Initiative Agreement. The language in this area of TFRS is correct. There may be some connections between the language used here and the language used in the confirmation modal window for transfers (the issue above). Please ensure that fixing the language for transfers does not change the language in used in the modal window for the New Initiative Agreement Issuance feature. 

This feature can be accessed by an IDIR user with the Gov't analyst role by going to the File Submissions page and then clicking on the 'New Initiative Agreement Issuance' button near the top of the page. 

Screenshot: 
<img width="1611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2k5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1199acaf9d1b5eed6591f1fd5ebf7b96677f4ac4/Screenshot%202024-01-11%20095901.png" alt="Screenshot 2024-01-11 095901.png" />

**Comment by justin-lepitzki** [comment] 2024-01-16 19:01
The correct labels & language are now showing in the confirmation modal window for when the analyst recommends recording a transfer. However, there is a new issue that relates to the "other considerations" section of this ticket. The button labels for when the analyst creates a new Initiative Agreement Issuance are now showing as "Recommend recording transfer". See the attached screenshot below. These labels are supposed to say "Recommend issuance". The label appears to be linked or have some connection between these two features, as when we change the label in one area (this card) it keeps causing changes to the labels in the other area. 

Please adjust the label for the Initiaitve Agreement Issuance back to "Recommend issuance" while also ensuring that the requirements of this card for the transfer labels is maintained. To access the Initiative Agreement Issuance feature, login as an IDIR user with the analyst role, then go to the File Submissions page and click on the 
'New Initiative Agreement Issuance' button. 

Screenshot of issue on the new Initiative Agreement Issuance page: <img width="1585" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnJQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be5fccdf23d0e97b1cf6c1a9b39e72b4ef80ba88/Screenshot%202024-01-16%20record%20transfer%20label.png" alt="Screenshot 2024-01-16 record transfer label.png" />

**Comment by hamed-valiollahi** [comment] 2024-01-16 21:14
@justin-lepitzki I appreciate your detailed explanation. I'll address the label issue. Thanks, Justin!

**Comment by justin-lepitzki** [comment] 2024-01-19 20:49
Reopened this issue as it appears that one of the button labels has reverted (see screenshot below). This label should say 'Recommend issuance'; the button labels in the confirmation modal window are correct. 

Steps to reproduce: 
IDIR user, government analyst role
1. Go to File Submissions page
2. Click on New Initiative Agreement Issuance button
3. Fill out required information and then click Save Draft
4. Open the draft transaction from the main transactions table
5. See incorrect button label

Note that this incorrect label only appears when saving a draft Initiative Agreement Issuance and then opening that draft transaction. The correct labels are showing in all other cases. 

Note 2: please ensure that changing this label does not change the labels in the transfer feature, which should correctly say "Recommend recording transfer" when the analyst is reviewing a transfer with the Submitted status. 

Screenshot of incorrect label: <img width="1582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWppQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2d74d369761a995ebdeda780865f1215fb9d1c0/screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-view-1263-2024-01-19-10_14_53.png" alt="screencapture-tfrs-dev-jan-apps-silver-devops-gov-bc-ca-credit-transactions-view-1263-2024-01-19-10_14_53.png" />

**Comment by hamed-valiollahi** [comment] 2024-01-23 18:55
@justin-lepitzki Sorry for the issue, Justin! The issue is now fixed. If there are any other issues, please let me know. Thank you!

**Closed** 2024-01-25 23:11 UTC
Labels: Task, High, Tested :), Added Banana 4 Scale
